"""empty message

Revision ID: 16d3b2fdf724
Revises: b942d2113257
Create Date: 2025-12-10 21:42:02.729581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16d3b2fdf724'
down_revision: Union[str, None] = 'b942d2113257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asteroid_models', sa.Column('estimated_diameter_km', sa.Float(), nullable=False, comment='Расчетный диаметр в километрах'))
    op.drop_column('asteroid_models', 'last_orbit_update')
    op.drop_column('asteroid_models', 'orbit_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asteroid_models', sa.Column('orbit_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Дополнительные орбитальные параметры в формате JSON'))
    op.add_column('asteroid_models', sa.Column('last_orbit_update', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата последнего обновления орбитальных данных из внешних источников'))
    op.drop_column('asteroid_models', 'estimated_diameter_km')
    # ### end Alembic commands ###
