"""empty message

Revision ID: 256e4da53b7e
Revises: 160e212eebe7
Create Date: 2025-12-10 22:17:55.152732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '256e4da53b7e'
down_revision: Union[str, None] = '160e212eebe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asteroid_models', sa.Column('mpc_number', sa.Integer(), nullable=False, comment='Уникальный номер из каталога Minor Planet Center'))
    op.add_column('asteroid_models', sa.Column('perihelion_au', sa.Float(), nullable=False, comment='Расстояние перигелия в астрономических единицах'))
    op.add_column('asteroid_models', sa.Column('aphelion_au', sa.Float(), nullable=False, comment='Расстояние афелия в астрономических единицах'))
    op.add_column('asteroid_models', sa.Column('earth_moid_au', sa.Float(), nullable=False, comment='Минимальное расстояние пересечения орбит с Землей (MOID)'))
    op.add_column('asteroid_models', sa.Column('absolute_magnitude', sa.Float(), nullable=False, comment='Абсолютная звездная величина (H)'))
    op.add_column('asteroid_models', sa.Column('estimated_diameter_km', sa.Float(), nullable=False, comment='Расчетный диаметр в километрах'))
    op.drop_constraint('asteroid_models_number_key', 'asteroid_models', type_='unique')
    op.create_unique_constraint(None, 'asteroid_models', ['mpc_number'])
    op.drop_column('asteroid_models', 'h_mag')
    op.drop_column('asteroid_models', 'number')
    op.drop_column('asteroid_models', 'aphelion')
    op.drop_column('asteroid_models', 'perihelion')
    op.drop_column('asteroid_models', 'earth_moid')
    op.drop_column('asteroid_models', 'diameter')
    op.drop_column('asteroid_models', 'last_update')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asteroid_models', sa.Column('last_update', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Дата последнего обновления'))
    op.add_column('asteroid_models', sa.Column('diameter', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Расчетный диаметр в километрах'))
    op.add_column('asteroid_models', sa.Column('earth_moid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Минимальное расстояние пересечения орбит с Землей (MOID)'))
    op.add_column('asteroid_models', sa.Column('perihelion', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Расстояние перигелия в астрономических единицах'))
    op.add_column('asteroid_models', sa.Column('aphelion', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Расстояние афелия в астрономических единицах'))
    op.add_column('asteroid_models', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False, comment='Уникальный номер из каталога Minor Planet Center'))
    op.add_column('asteroid_models', sa.Column('h_mag', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Абсолютная звездная величина (H)'))
    op.drop_constraint(None, 'asteroid_models', type_='unique')
    op.create_unique_constraint('asteroid_models_number_key', 'asteroid_models', ['number'])
    op.drop_column('asteroid_models', 'estimated_diameter_km')
    op.drop_column('asteroid_models', 'absolute_magnitude')
    op.drop_column('asteroid_models', 'earth_moid_au')
    op.drop_column('asteroid_models', 'aphelion_au')
    op.drop_column('asteroid_models', 'perihelion_au')
    op.drop_column('asteroid_models', 'mpc_number')
    # ### end Alembic commands ###
