"""empty message

Revision ID: 376503f3e819
Revises: 29f9f0f4027e
Create Date: 2025-12-11 20:13:20.553006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '376503f3e819'
down_revision: Union[str, None] = '29f9f0f4027e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asteroid_models', 'albedo',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_comment='Альбедо (отражательная способность), если известно')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asteroid_models', 'albedo',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_comment='Альбедо (отражательная способность), если известно')
    # ### end Alembic commands ###
