"""empty message

Revision ID: 4a982ffeefdf
Revises: a45fc6709bad
Create Date: 2025-12-28 23:07:41.591541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a982ffeefdf'
down_revision: Union[str, None] = 'a45fc6709bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asteroid_models', sa.Column('diameter_source', sa.String(length=20), nullable=False, comment="Источник данных о диаметре: 'measured', 'computed', 'calculated'"))
    op.alter_column('asteroid_models', 'designation',
               existing_type=sa.VARCHAR(length=50),
               comment="Обозначение NASA (напр., '99942', '2025 XN4')",
               existing_comment="Обозначение NASA (напр., '99942', '2025 XN4') - первичный идентификатор",
               existing_nullable=False)
    op.alter_column('asteroid_models', 'perihelion_au',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Расстояние перигелия в астрономических единицах',
               existing_comment='Расстояние перигелия в астрономических единицах (может быть NULL)',
               existing_nullable=True)
    op.alter_column('asteroid_models', 'aphelion_au',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Расстояние афелия в астрономических единицах',
               existing_comment='Расстояние афелия в астрономических единицах (может быть NULL)',
               existing_nullable=True)
    op.alter_column('asteroid_models', 'accurate_diameter',
               existing_type=sa.BOOLEAN(),
               comment='Диаметр точный или же рассчитан по стандартному альбедо',
               existing_comment='Диаметр точный или же расчитан нами по стандартному альбедо',
               existing_nullable=False)
    op.add_column('close_approach_models', sa.Column('asteroid_name', sa.String(length=100), nullable=True, comment='Полное имя астероида из CAD API'))
    op.add_column('close_approach_models', sa.Column('data_source', sa.String(length=50), nullable=False, comment='Источник данных (NASA CAD API или другой)'))
    op.alter_column('close_approach_models', 'asteroid_designation',
               existing_type=sa.VARCHAR(length=50),
               comment='Обозначение NASA астероида (из CAD API: asteroid_number)',
               existing_comment='Обозначение NASA астероида (дублируется для удобства запросов)',
               existing_nullable=False)
    op.add_column('threat_assessment_models', sa.Column('asteroid_id', sa.Integer(), nullable=False, comment='Ссылка на астероид'))
    op.add_column('threat_assessment_models', sa.Column('designation', sa.String(length=50), nullable=False, comment="Обозначение астероида (например, '2023 DW')"))
    op.add_column('threat_assessment_models', sa.Column('fullname', sa.String(length=100), nullable=False, comment='Полное название астероида'))
    op.add_column('threat_assessment_models', sa.Column('ip', sa.Float(), nullable=False, comment='Вероятность столкновения (impact probability)'))
    op.add_column('threat_assessment_models', sa.Column('ts_max', sa.Integer(), nullable=False, comment='Максимальное значение по Туринской шкале'))
    op.add_column('threat_assessment_models', sa.Column('ps_max', sa.Float(), nullable=False, comment='Максимальное значение по Палермской шкале'))
    op.add_column('threat_assessment_models', sa.Column('diameter_km', sa.Float(), nullable=False, comment='Диаметр астероида в километрах (из Sentry)'))
    op.add_column('threat_assessment_models', sa.Column('velocity_km_s', sa.Float(), nullable=False, comment='Скорость на бесконечности в км/с'))
    op.add_column('threat_assessment_models', sa.Column('absolute_magnitude', sa.Float(), nullable=False, comment='Абсолютная звездная величина (H) из Sentry'))
    op.add_column('threat_assessment_models', sa.Column('n_imp', sa.Integer(), nullable=False, comment='Количество сценариев столкновения'))
    op.add_column('threat_assessment_models', sa.Column('impact_years', sa.JSON(), nullable=False, comment='Года возможных столкновений (JSON-массив)'))
    op.add_column('threat_assessment_models', sa.Column('last_obs', sa.String(length=20), nullable=False, comment='Дата последнего наблюдения'))
    op.add_column('threat_assessment_models', sa.Column('threat_level_ru', sa.String(length=50), nullable=False, comment='Уровень угрозы на русском'))
    op.add_column('threat_assessment_models', sa.Column('torino_scale_ru', sa.Text(), nullable=False, comment='Описание по Туринской шкале на русском'))
    op.add_column('threat_assessment_models', sa.Column('impact_probability_text_ru', sa.Text(), nullable=False, comment='Текст вероятности на русском'))
    op.drop_index('ix_threat_assessment_models_approach_id', table_name='threat_assessment_models')
    op.create_index(op.f('ix_threat_assessment_models_asteroid_id'), 'threat_assessment_models', ['asteroid_id'], unique=False)
    op.create_index(op.f('ix_threat_assessment_models_designation'), 'threat_assessment_models', ['designation'], unique=False)
    op.create_unique_constraint('uq_threat_assessment_designation', 'threat_assessment_models', ['designation'])
    op.drop_constraint('threat_assessment_models_approach_id_fkey', 'threat_assessment_models', type_='foreignkey')
    op.create_foreign_key(None, 'threat_assessment_models', 'asteroid_models', ['asteroid_id'], ['id'], ondelete='CASCADE')
    op.drop_column('threat_assessment_models', 'approach_id')
    op.drop_column('threat_assessment_models', 'threat_level')
    op.drop_column('threat_assessment_models', 'calculation_input_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threat_assessment_models', sa.Column('calculation_input_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='Хеш входных данных для отслеживания изменений'))
    op.add_column('threat_assessment_models', sa.Column('threat_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment="Уровень угрозы: 'низкий', 'средний', 'высокий', 'критический'"))
    op.add_column('threat_assessment_models', sa.Column('approach_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Ссылка на сближение (уникальная)'))
    op.drop_constraint(None, 'threat_assessment_models', type_='foreignkey')
    op.create_foreign_key('threat_assessment_models_approach_id_fkey', 'threat_assessment_models', 'close_approach_models', ['approach_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_threat_assessment_designation', 'threat_assessment_models', type_='unique')
    op.drop_index(op.f('ix_threat_assessment_models_designation'), table_name='threat_assessment_models')
    op.drop_index(op.f('ix_threat_assessment_models_asteroid_id'), table_name='threat_assessment_models')
    op.create_index('ix_threat_assessment_models_approach_id', 'threat_assessment_models', ['approach_id'], unique=True)
    op.drop_column('threat_assessment_models', 'impact_probability_text_ru')
    op.drop_column('threat_assessment_models', 'torino_scale_ru')
    op.drop_column('threat_assessment_models', 'threat_level_ru')
    op.drop_column('threat_assessment_models', 'last_obs')
    op.drop_column('threat_assessment_models', 'impact_years')
    op.drop_column('threat_assessment_models', 'n_imp')
    op.drop_column('threat_assessment_models', 'absolute_magnitude')
    op.drop_column('threat_assessment_models', 'velocity_km_s')
    op.drop_column('threat_assessment_models', 'diameter_km')
    op.drop_column('threat_assessment_models', 'ps_max')
    op.drop_column('threat_assessment_models', 'ts_max')
    op.drop_column('threat_assessment_models', 'ip')
    op.drop_column('threat_assessment_models', 'fullname')
    op.drop_column('threat_assessment_models', 'designation')
    op.drop_column('threat_assessment_models', 'asteroid_id')
    op.alter_column('close_approach_models', 'asteroid_designation',
               existing_type=sa.VARCHAR(length=50),
               comment='Обозначение NASA астероида (дублируется для удобства запросов)',
               existing_comment='Обозначение NASA астероида (из CAD API: asteroid_number)',
               existing_nullable=False)
    op.drop_column('close_approach_models', 'data_source')
    op.drop_column('close_approach_models', 'asteroid_name')
    op.alter_column('asteroid_models', 'accurate_diameter',
               existing_type=sa.BOOLEAN(),
               comment='Диаметр точный или же расчитан нами по стандартному альбедо',
               existing_comment='Диаметр точный или же рассчитан по стандартному альбедо',
               existing_nullable=False)
    op.alter_column('asteroid_models', 'aphelion_au',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Расстояние афелия в астрономических единицах (может быть NULL)',
               existing_comment='Расстояние афелия в астрономических единицах',
               existing_nullable=True)
    op.alter_column('asteroid_models', 'perihelion_au',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Расстояние перигелия в астрономических единицах (может быть NULL)',
               existing_comment='Расстояние перигелия в астрономических единицах',
               existing_nullable=True)
    op.alter_column('asteroid_models', 'designation',
               existing_type=sa.VARCHAR(length=50),
               comment="Обозначение NASA (напр., '99942', '2025 XN4') - первичный идентификатор",
               existing_comment="Обозначение NASA (напр., '99942', '2025 XN4')",
               existing_nullable=False)
    op.drop_column('asteroid_models', 'diameter_source')
    # ### end Alembic commands ###
