"""empty message

Revision ID: 8e24e26fea5c
Revises: 9179fc966a09
Create Date: 2025-12-14 14:58:38.461968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e24e26fea5c'
down_revision: Union[str, None] = '9179fc966a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('close_approach_models', 'approach_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='Точное время максимального сближения',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('close_approach_models', 'approach_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='Точное время максимального сближения',
               existing_nullable=False)
    # ### end Alembic commands ###
