"""empty message

Revision ID: 9179fc966a09
Revises: a71d225ebe6b
Create Date: 2025-12-13 23:51:49.508936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9179fc966a09'
down_revision: Union[str, None] = 'a71d225ebe6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_asteroid_approach_time', 'close_approach_models', ['asteroid_id', 'approach_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_asteroid_approach_time', 'close_approach_models', type_='unique')
    # ### end Alembic commands ###
