"""empty message

Revision ID: 942eb0dd17c0
Revises: 256e4da53b7e
Create Date: 2025-12-10 22:20:06.868874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '942eb0dd17c0'
down_revision: Union[str, None] = '256e4da53b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asteroid_models', sa.Column('last_updated', sa.DateTime(), nullable=False, comment='Дата последнего обновления данных'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asteroid_models', 'last_updated')
    # ### end Alembic commands ###
