"""empty message

Revision ID: a45fc6709bad
Revises: 8e24e26fea5c
Create Date: 2025-12-17 19:31:52.194538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45fc6709bad'
down_revision: Union[str, None] = '8e24e26fea5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asteroid_models', sa.Column('orbit_id', sa.String(length=20), nullable=True, comment='ID орбиты из NASA SBDB'))
    op.add_column('asteroid_models', sa.Column('orbit_class', sa.String(length=50), nullable=True, comment="Класс орбиты (напр., 'Apollo', 'Aten', 'Amor')"))
    op.alter_column('asteroid_models', 'designation',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment="Обозначение NASA (напр., '99942', '2025 XN4') - первичный идентификатор",
               existing_comment='Временное обозначение')
    op.alter_column('asteroid_models', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment="Собственное название астероида (напр., 'Apophis')",
               existing_comment='Собственное название астероида',
               existing_nullable=True)
    op.alter_column('asteroid_models', 'perihelion_au',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               comment='Расстояние перигелия в астрономических единицах (может быть NULL)',
               existing_comment='Расстояние перигелия в астрономических единицах')
    op.alter_column('asteroid_models', 'aphelion_au',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               comment='Расстояние афелия в астрономических единицах (может быть NULL)',
               existing_comment='Расстояние афелия в астрономических единицах')
    op.alter_column('asteroid_models', 'earth_moid_au',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_comment='Минимальное расстояние пересечения орбит с Землей (MOID)')
    op.drop_constraint('asteroid_models_mpc_number_key', 'asteroid_models', type_='unique')
    op.create_index(op.f('ix_asteroid_models_designation'), 'asteroid_models', ['designation'], unique=True)
    op.create_unique_constraint('uq_asteroid_designation', 'asteroid_models', ['designation'])
    op.drop_column('asteroid_models', 'is_pha')
    op.drop_column('asteroid_models', 'is_neo')
    op.drop_column('asteroid_models', 'mpc_number')
    op.add_column('close_approach_models', sa.Column('asteroid_designation', sa.String(length=50), nullable=False, comment='Обозначение NASA астероида (дублируется для удобства запросов)'))
    op.create_index(op.f('ix_close_approach_models_asteroid_designation'), 'close_approach_models', ['asteroid_designation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_close_approach_models_asteroid_designation'), table_name='close_approach_models')
    op.drop_column('close_approach_models', 'asteroid_designation')
    op.add_column('asteroid_models', sa.Column('mpc_number', sa.INTEGER(), autoincrement=False, nullable=False, comment='Уникальный номер из каталога Minor Planet Center'))
    op.add_column('asteroid_models', sa.Column('is_neo', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Является ли околоземным объектом (NEO)'))
    op.add_column('asteroid_models', sa.Column('is_pha', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Является ли потенциально опасным (PHA)'))
    op.drop_constraint('uq_asteroid_designation', 'asteroid_models', type_='unique')
    op.drop_index(op.f('ix_asteroid_models_designation'), table_name='asteroid_models')
    op.create_unique_constraint('asteroid_models_mpc_number_key', 'asteroid_models', ['mpc_number'])
    op.alter_column('asteroid_models', 'earth_moid_au',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_comment='Минимальное расстояние пересечения орбит с Землей (MOID)')
    op.alter_column('asteroid_models', 'aphelion_au',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               comment='Расстояние афелия в астрономических единицах',
               existing_comment='Расстояние афелия в астрономических единицах (может быть NULL)')
    op.alter_column('asteroid_models', 'perihelion_au',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               comment='Расстояние перигелия в астрономических единицах',
               existing_comment='Расстояние перигелия в астрономических единицах (может быть NULL)')
    op.alter_column('asteroid_models', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Собственное название астероида',
               existing_comment="Собственное название астероида (напр., 'Apophis')",
               existing_nullable=True)
    op.alter_column('asteroid_models', 'designation',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment='Временное обозначение',
               existing_comment="Обозначение NASA (напр., '99942', '2025 XN4') - первичный идентификатор")
    op.drop_column('asteroid_models', 'orbit_class')
    op.drop_column('asteroid_models', 'orbit_id')
    # ### end Alembic commands ###
