"""Create asteroid, close_approach and threat_assessment tables

Revision ID: b2ea6928d842
Revises: d7a111e56231
Create Date: 2025-12-05 20:58:14.363001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ea6928d842'
down_revision: Union[str, None] = 'd7a111e56231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asteroid_models',
    sa.Column('mpc_number', sa.Integer(), nullable=False, comment='Уникальный номер из каталога Minor Planet Center'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='Собственное название астероида'),
    sa.Column('designation', sa.String(length=50), nullable=True, comment='Временное обозначение'),
    sa.Column('perihelion_au', sa.Float(), nullable=False, comment='Расстояние перигелия в астрономических единицах'),
    sa.Column('aphelion_au', sa.Float(), nullable=False, comment='Расстояние афелия в астрономических единицах'),
    sa.Column('earth_moid_au', sa.Float(), nullable=False, comment='Минимальное расстояние пересечения орбит с Землей (MOID)'),
    sa.Column('absolute_magnitude', sa.Float(), nullable=False, comment='Абсолютная звездная величина (H)'),
    sa.Column('estimated_diameter_km', sa.Float(), nullable=False, comment='Расчетный диаметр в километрах'),
    sa.Column('albedo', sa.Float(), nullable=True, comment='Альбедо (отражательная способность), если известно'),
    sa.Column('is_neo', sa.Boolean(), nullable=False, comment='Является ли околоземным объектом (NEO)'),
    sa.Column('is_pha', sa.Boolean(), nullable=False, comment='Является ли потенциально опасным (PHA)'),
    sa.Column('orbit_data', sa.JSON(), nullable=True, comment='Дополнительные орбитальные параметры в формате JSON'),
    sa.Column('last_orbit_update', sa.DateTime(), nullable=True, comment='Дата последнего обновления орбитальных данных из внешних источников'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('aphelion_au > perihelion_au', name='check_aphelion_gt_perihelion'),
    sa.CheckConstraint('earth_moid_au >= 0', name='check_moid_non_negative'),
    sa.CheckConstraint('perihelion_au > 0', name='check_perihelion_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mpc_number')
    )
    op.create_table('close_approach_models',
    sa.Column('asteroid_id', sa.Integer(), nullable=False, comment='Ссылка на астероид'),
    sa.Column('approach_time', sa.DateTime(timezone=True), nullable=False, comment='Точное время максимального сближения'),
    sa.Column('distance_au', sa.Float(), nullable=False, comment='Расстояние в астрономических единицах'),
    sa.Column('distance_km', sa.Float(), nullable=False, comment='Расстояние в километрах (рассчитанное поле)'),
    sa.Column('velocity_km_s', sa.Float(), nullable=False, comment='Относительная скорость в км/с'),
    sa.Column('calculation_batch_id', sa.String(length=50), nullable=True, comment='Идентификатор партии расчета (для отслеживания)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asteroid_id'], ['asteroid_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_close_approach_models_approach_time'), 'close_approach_models', ['approach_time'], unique=False)
    op.create_index(op.f('ix_close_approach_models_asteroid_id'), 'close_approach_models', ['asteroid_id'], unique=False)
    op.create_table('threat_assessment_models',
    sa.Column('approach_id', sa.Integer(), nullable=False, comment='Ссылка на сближение (уникальная)'),
    sa.Column('threat_level', sa.String(length=20), nullable=False, comment="Уровень угрозы: 'низкий', 'средний', 'высокий', 'критический'"),
    sa.Column('impact_category', sa.String(length=20), nullable=False, comment="Категория воздействия: 'локальный', 'региональный', 'глобальный'"),
    sa.Column('energy_megatons', sa.Float(), nullable=False, comment='Энергия воздействия в мегатоннах тротила'),
    sa.Column('calculation_input_hash', sa.String(length=64), nullable=True, comment='Хеш входных данных для отслеживания изменений'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("impact_category IN ('локальный', 'региональный', 'глобальный')", name='check_impact_category'),
    sa.CheckConstraint("threat_level IN ('низкий', 'средний', 'высокий', 'критический')", name='check_threat_level'),
    sa.CheckConstraint('energy_megatons >= 0', name='check_energy_non_negative'),
    sa.ForeignKeyConstraint(['approach_id'], ['close_approach_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_assessment_models_approach_id'), 'threat_assessment_models', ['approach_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_assessment_models_approach_id'), table_name='threat_assessment_models')
    op.drop_table('threat_assessment_models')
    op.drop_index(op.f('ix_close_approach_models_asteroid_id'), table_name='close_approach_models')
    op.drop_index(op.f('ix_close_approach_models_approach_time'), table_name='close_approach_models')
    op.drop_table('close_approach_models')
    op.drop_table('asteroid_models')
    # ### end Alembic commands ###
