"""empty message

Revision ID: b942d2113257
Revises: b2ea6928d842
Create Date: 2025-12-06 22:03:38.158358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b942d2113257'
down_revision: Union[str, None] = 'b2ea6928d842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asteroid_models', sa.Column('accurate_diameter', sa.Boolean(), nullable=False, comment='Диаметр точный или же расчитан нами по стандартному альбедо'))
    op.drop_column('asteroid_models', 'estimated_diameter_km')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asteroid_models', sa.Column('estimated_diameter_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Расчетный диаметр в километрах'))
    op.drop_column('asteroid_models', 'accurate_diameter')
    # ### end Alembic commands ###
