"""empty message

Revision ID: ce0e4aebe81a
Revises: 001_timezone_aware_approach_time
Create Date: 2026-04-02 16:30:44.308536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce0e4aebe81a'
down_revision: Union[str, None] = '001_timezone_aware_approach_time'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('threat_assessment_models', 'sentry_last_update',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='Время последнего обновления данных из Sentry API',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('threat_assessment_models', 'sentry_last_update',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='Время последнего обновления данных из Sentry API',
               existing_nullable=False)
    # ### end Alembic commands ###
