"""fix threat assessment model and various issues

Revision ID: f5d5c8606975
Revises: 4a982ffeefdf
Create Date: 2026-01-24 21:56:41.237807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d5c8606975'
down_revision: Union[str, None] = '4a982ffeefdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('close_approach_models', 'asteroid_designation',
               existing_type=sa.VARCHAR(length=50),
               comment='Обозначение NASA астероида',
               existing_comment='Обозначение NASA астероида (из CAD API: asteroid_number)',
               existing_nullable=False)
    op.add_column('threat_assessment_models', sa.Column('diameter', sa.Float(), nullable=False, comment='Диаметр астероида в километрах (из Sentry)'))
    op.add_column('threat_assessment_models', sa.Column('v_inf', sa.Float(), nullable=False, comment='Скорость на бесконечности в км/с'))
    op.add_column('threat_assessment_models', sa.Column('h', sa.Float(), nullable=False, comment='Абсолютная звездная величина (H) из Sentry'))
    op.add_column('threat_assessment_models', sa.Column('sentry_last_update', sa.DateTime(), nullable=False, comment='Время последнего обновления данных из Sentry API'))
    op.alter_column('threat_assessment_models', 'asteroid_id',
               existing_type=sa.INTEGER(),
               comment='Ссылка на астероид (One-to-One)',
               existing_comment='Ссылка на астероид',
               existing_nullable=False)
    op.drop_index('ix_threat_assessment_models_asteroid_id', table_name='threat_assessment_models')
    op.create_index(op.f('ix_threat_assessment_models_asteroid_id'), 'threat_assessment_models', ['asteroid_id'], unique=True)
    op.create_unique_constraint('uq_threat_assessment_asteroid', 'threat_assessment_models', ['asteroid_id'])
    op.drop_column('threat_assessment_models', 'absolute_magnitude')
    op.drop_column('threat_assessment_models', 'velocity_km_s')
    op.drop_column('threat_assessment_models', 'diameter_km')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threat_assessment_models', sa.Column('diameter_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Диаметр астероида в километрах (из Sentry)'))
    op.add_column('threat_assessment_models', sa.Column('velocity_km_s', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Скорость на бесконечности в км/с'))
    op.add_column('threat_assessment_models', sa.Column('absolute_magnitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='Абсолютная звездная величина (H) из Sentry'))
    op.drop_constraint('uq_threat_assessment_asteroid', 'threat_assessment_models', type_='unique')
    op.drop_index(op.f('ix_threat_assessment_models_asteroid_id'), table_name='threat_assessment_models')
    op.create_index('ix_threat_assessment_models_asteroid_id', 'threat_assessment_models', ['asteroid_id'], unique=False)
    op.alter_column('threat_assessment_models', 'asteroid_id',
               existing_type=sa.INTEGER(),
               comment='Ссылка на астероид',
               existing_comment='Ссылка на астероид (One-to-One)',
               existing_nullable=False)
    op.drop_column('threat_assessment_models', 'sentry_last_update')
    op.drop_column('threat_assessment_models', 'h')
    op.drop_column('threat_assessment_models', 'v_inf')
    op.drop_column('threat_assessment_models', 'diameter')
    op.alter_column('close_approach_models', 'asteroid_designation',
               existing_type=sa.VARCHAR(length=50),
               comment='Обозначение NASA астероида (из CAD API: asteroid_number)',
               existing_comment='Обозначение NASA астероида',
               existing_nullable=False)
    # ### end Alembic commands ###
